debian/dbus.posinst: When triggered only poke the dbus-daemon, don't run update-rc.d/invoke-rc.d as added by dh_installinit. This prevent some odd-corner when being triggered during init system upgrade (Closes: #754404)

diff --git a/debian/dbus.postinst b/debian/dbus.postinst
--- a/debian/dbus.postinst
+++ b/debian/dbus.postinst
@@ -8,6 +8,25 @@ MESSAGEUSER=messagebus
 MESSAGEHOME=/var/run/dbus
 LAUNCHER=/usr/lib/dbus-1.0/dbus-daemon-launch-helper
 
+# This is what the init script would do, but it's simpler (and less
+# dependent on sysvinit vs. Upstart vs. etc.) if we do it directly. It is not
+# conditional on "$1" because it's also the right thing to do for the
+# /etc/dbus-1/system.d and /usr/share/dbus-1/system-services triggers.
+#
+# If it's not running (perhaps we're in a chroot) this will just fail
+# harmlessly, so there's no need to condition on status.
+reload_dbus_config() {
+    dbus-send --print-reply --system --type=method_call \
+        --dest=org.freedesktop.DBus \
+        / org.freedesktop.DBus.ReloadConfig > /dev/null || true
+}
+
+
+if [ "$1" = triggered ]; then
+    reload_dbus_config
+    exit 0
+fi
+
 if [ "$1" = configure ]; then
     adduser --system \
             --quiet \
@@ -45,15 +64,6 @@ if [ "$1" = configure ] && [ -n "$2" ]; then
     fi
 fi
 
-# This is what the init script would do, but it's simpler (and less
-# dependent on sysvinit vs. Upstart vs. etc.) if we do it directly. It is not
-# conditional on "$1" because it's also the right thing to do for the
-# /etc/dbus-1/system.d and /usr/share/dbus-1/system-services triggers.
-#
-# If it's not running (perhaps we're in a chroot) this will just fail
-# harmlessly, so there's no need to condition on status.
-dbus-send --print-reply --system --type=method_call \
-    --dest=org.freedesktop.DBus \
-    / org.freedesktop.DBus.ReloadConfig > /dev/null || true
+reload_dbus_config
 
 #DEBHELPER#
